### ISSUE TITLE
Search by time

### ISSUE THREAD

**Issue by Acrobat622** [CS2103jan2015-t09-2j/main#171]
Allow user to search time:
need to edit memory as well
1. start time and end time, find tasks within this range
2. search a task happens on that day

**Comment by Acrobat622** [comment]
i will help ya

**Comment by Acrobat622** [comment]
We can now search date, but i will keep on working on search on specific time (hh:mm) periods
We also need to think about how to search "this week" or "this month"

**Comment by Weinilin** [comment]
this week and this month, i have implemented it in parser. Hope it will be useful for ur search.
